# Generated by Django 5.2.8 on 2025-11-19 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_horas', models.IntegerField()),
                ('fecha', models.DateField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='transport.carro')),
                ('ciudad_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_destino', to='transport.ciudad')),
                ('ciudad_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_origen', to='transport.ciudad')),
            ],
        ),
    ]
